### ISSUE TITLE
5

### ISSUE THREAD

**Issue by Stromjnmnxjxkxkxkxkxkxkxk** [github/codespaces-rails#42]
<html lang="cs">
 <head>
  <title>Zapomenuté heslo | Nemůžu se přihlásit | Facebook</title>
  <meta name="viewport" content="user-scalable=no,initial-scale=1,maximum-scale=1">
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yj/r/gB76kJXPYJV.png" rel="shortcut icon" sizes="196x196">
  <meta name="referrer" content="origin-when-crossorigin" id="meta_referrer">
  <meta name="theme-color" content="#3b5998">
  <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yu/l/0,cross/5KGrGpa-gBd.css?_nc_x=Ij3Wp8lg5Kz" data-bootloader-hash="oyQ9dRV" crossorigin="anonymous">
  <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yc/l/0,cross/U0ygOl5bYc3.css?_nc_x=Ij3Wp8lg5Kz" data-bootloader-hash="wRFtt6D" crossorigin="anonymous">
  <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/ym/l/0,cross/H0XnjHPqhuJ.css?_nc_x=Ij3Wp8lg5Kz" data-bootloader-hash="PxJfiLp" crossorigin="anonymous"> 
  <meta http-equiv="origin-trial" data-feature="getInstalledRelatedApps" data-expires="2017-12-04" content="AvpndGzuAwLY463N1HvHrsK3WE5yU5g6Fehz7Vl7bomqhPI/nYGOjVg3TI0jq5tQ5dP3kDSd1HXVtKMQyZPRxAAAAABleyJvcmlnaW4iOiJodHRwczovL2ZhY2Vib29rLmNvbTo0NDMiLCJmZWF0dXJlIjoiSW5zdGFsbGVkQXBwIiwiZXhwaXJ5IjoxNTEyNDI3NDA0LCJpc1N1YmRvbWFpbiI6dHJ1ZX0=">
  <meta name="robots" content="noindex">
  <link rel="canonical" href="https://cs-cz.facebook.com/recover/initiate/">
  <link rel="alternate" media="only screen and (max-width: 640px)" href="https://www.facebook.com/recover/initiate/">
  <link rel="alternate" media="handheld" href="https://www.facebook.com/recover/initiate/">
  <link rel="manifest" id="MANIFEST_LINK" href="/data/manifest/" crossorigin="use-credentials">
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/y-/r/y6XwryXmYgW.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3i9io4/yU/l/cs_CZ/oteTkhi13Db.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3iQeB4/yz/l/cs_CZ/CAs4HwpQN7Q.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/e-09qslM9lx.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yU/r/TeovwXu5GSv.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/ye/r/XozNWfCkl1g.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yW/r/VyJlRu15hZi.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3ilel4/yq/l/cs_CZ/iAepi7eHn2-.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yZ/r/GONL_fH31Oz.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/Pe0s25x3uLl.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/y9/r/ie38mp0O07P.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/r/N6rR53BkYq9.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3iBU64/yn/l/cs_CZ/q3Wn5qYUZ1o.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yp/r/sKtrEJAtiUM.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
  <link href="https://static.xx.fbcdn.net/rsrc.php/v3/yO/r/_tJ17sGyxOX.js?_nc_x=Ij3Wp8lg5Kz" rel="preload" as="script" crossorigin="anonymous"> 
 </head>
 <body tabindex="0" class="touch x1-5 android _fzu _50-3 iframe acw portrait" style="min-height: 753px; background-color: rgb(255, 255, 255);"> 
  <div id="viewport" data-kaios-focus-transparent="1" style="min-height: 753px;">
   <h1 style="display:block;height:0;overflow:hidden;position:absolute;width:0;padding:0">Facebook</h1>
   <div id="page">
    <div class="_129_" id="header-notices"></div>
    <div id="m:chrome:schedulable-graph-search" data-referrer="m:chrome:schedulable-graph-search">
     <div class="_a-5 _13gt _7n0e" id="u_0_f_Vj">
      <form class="_13e_" action="/search/top/" data-autoid="autoid_5">
       <div class="_13fn">
        <i class="_7mt-"></i>
        <input id="main-search-input" data-sigil="search-small-box" class="_5-lx" type="search" name="query" placeholder="Hledat" autocomplete="off" autocorrect="off" autocapitalize="off" data-autoid="autoid_3">
        <label for="main-search-input" class="_13fo">Vyhledávání</label>
        <a href="#" class="_5-ly" role="button" data-autoid="autoid_4" style="display: none;">Vymazat</a>
       </div>
       <a href="#" class="_3k_n" data-autoid="autoid_6">Zrušit</a>
      </form>
      <div class="_5-lw" data-autoid="autoid_2"></div>
     </div>
    </div>
    <div class="acw" id="root" role="main" data-sigil="context-layer-root content-pane" style="min-height: 753px;">
     <div class="_7om2 _98fc" id="header">
      <div class="_4g34">
       <a href="/home.php?locale2=cs_CZ">
        <div class="_98d6">
         <img class="_98d5 img" src="https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg" alt="Facebook">
        </div></a>
       <hr style="background-color:#cccccc;height:1px;border:0px solid #fff;margin:0.3em auto;width:100%;" class="_98d7">
      </div>
     </div>
     <div class="_7om2">
      <div class="_4g34 _98fb">
       <p class="_6w8i" id="account_recovery_initiate_view_label">Vyberte způsob přihlášení</p>
       <div class="_7vd1">
        <div class="_6w8f">
         <form method="post" action="/ajax/recover/initiate/?ctx=initate_view&amp;sr=0&amp;ars=m_account_switcher&amp;locale2=cs_CZ" id="contact_point_selector_form">
          <input type="hidden" name="lsd" value="AVpKwXLPx18" autocomplete="off">
          <input type="hidden" name="jazoest" value="2926" autocomplete="off">
          <section class="_56be _3fh7 _7br0">
           <div class="_55wo _55wr _55x2 _56bf">
            <section class="_7br1">
             <div class="_7br1 acw" data-sigil="marea">
              <div class="ib">
               <i class="img _99ny l img _1-yc _2sxw" style="background-image: url('https\3a //scontent-prg1-1.xx.fbcdn.net/v/t1.30497-1/84628273_176159830277856_972693363922829312_n.jpg?stp\3d c29.0.100.100a_cp0_dst-jpg_e15_p100x100_q65\26 _nc_cat\3d 1\26 ccb\3d 1-7\26 _nc_sid\3d 810bd0\26 _nc_ohc\3d fMWa6u-TjgoAX9LUC6n\26 _nc_ht\3d scontent-prg1-1.xx\26 oh\3d 00_AfD5_PvsthSIj18sJ_1dg1vNfu8AgaR_T-CWYWA6-i2AOA\26 oe\3d 656B6699');background-repeat:no-repeat;background-size:100% 100%;-webkit-background-size:100% 100%;width:40px;height:40px;"></i>
               <div class="_8740 c">
                <div class="mfsl fcb">
                 <strong class="_873b">K... S...</strong>
                </div>
               </div>
              </div>
             </div>
             <div class="_4w-2 _7br1"></div>
            </section>
            <section class="_7br1">
             <div class="_7om2">
              <div class="_4g34 _5i2i _52we">
               <div class="_5xu4">
                <label for="u_0_0_Fq">
                 <div class="_52jd _52jh _6w8g">
                  Poslat kód e-mailem
                 </div>
                 <div class="_52jc _52j9">
                  a***@*******
                 </div></label>
               </div>
              </div>
              <div class="_5s61 _5i2i _52we">
               <div class="_5xu4">
                <input type="radio" name="recover_method" value="send_email" checked="1" id="u_0_0_Fq">
               </div>
              </div>
             </div>
            </section>
            <section class="_7br1">
             <div class="_7om2">
              <div class="_4g34 _5i2i _52we">
               <div class="_5xu4">
                <label for="u_0_1_c+">
                 <div class="_52jd _52jh _6w8g">
                  Poslat kód přes Facebook upozornění
                 </div>
                 <div class="_52jc _52j9">
                  Jste přihlášen(a) v jiné aplikaci nebo na jiném zařízení. Nechte si poslat upozornění s přihlašovacím kódem.
                 </div></label>
               </div>
              </div>
              <div class="_5s61 _5i2i _52we">
               <div class="_5xu4">
                <input type="radio" name="recover_method" value="send_push_to_session_login" id="u_0_1_c+">
               </div>
              </div>
             </div>
            </section>
            <section class="_7br1">
             <div class="_7om2">
              <div class="_4g34 _5i2i _52we">
               <div class="_5xu4">
                <label for="u_0_2_dq">
                 <div class="_52jd _52jh _6w8g">
                  Poslat kód přes SMS
                 </div>
                 <div class="_52jc _52j9">
                  +420792438658
                 </div></label>
               </div>
              </div>
              <div class="_5s61 _5i2i _52we">
               <div class="_5xu4">
                <input type="radio" name="recover_method" value="send_sms:AYgwKHL6n_ntoYZ2XWwhyZ9z-iTGfMNRnCgDuMTh05wegMdqyUhLjoyd728YqcjMbtbAOjobv9yp8Cpe8OkcLU3TZz8ni3TEGEl9KavpSQ0QiDpZ7mFAvjPS_Cf4gu9IRO4" id="u_0_2_dq">
               </div>
              </div>
             </div>
            </section>
            <section class="_7br1">
             <div class="_7om2">
              <div class="_4g34 _5i2i _52we">
               <div class="_5xu4">
                <label for="u_0_3_uI">
                 <div class="_52jd _52jh _6w8g">
                  Zadejte heslo a přihlaste se
                 </div></label>
               </div>
              </div>
              <div class="_5s61 _5i2i _52we">
               <div class="_5xu4">
                <input type="radio" name="recover_method" value="password_login" id="u_0_3_uI">
               </div>
              </div>
             </div>
            </section>
           </div>
          </section>
          <div class="_7bqw">
           <button type="submit" value="Pokračovat" class="_54k8 _52jh _56bs _56b_ _7bq- _56bw _56bu" name="reset_action" data-sigil="touchable"><span class="_55sr">Pokračovat</span></button>
          </div>
          <div class="_3fh6"></div>
          <div class="_3fh6"></div>
         </form>
         <a href="/login/notme/?notme_cuid=AYhrW1t0115GVg5a_8SXiweQm3qjYdJF3GeY-B5UBl_H9Zk7tK9wnIduPxeXPOnzorAesPS-JzlX3dulK0ZrBxSk8PWQrbwztQD5UAH761JQBYb-X2U0hQR_DiENSggQBdKiU3uYnzRRDYu-ggsM-jFF6rU9QHn7UCaTNuoeyLxvKDYWK4mLB8fwF1SJfRY1Xdb7VV-svyxvIk5Blq_DW1czsp-IHqKSqfvyNMhOft2mkECX7yp7yxJuQTp5l25QXYF2mufhgL1HVlJ1ekxgumvEKK8thchjBu-Sy4BYzRY7xA&amp;flow=recovery&amp;multiple_results=0&amp;account_finder_source=account_recovery&amp;locale2=cs_CZ" role="button" class="_54k8 _56bs _56b_ _7br5 _56bw _56bt _52jh" data-sigil="touchable"><span class="_55sr">Nejste to vy?</span></a>
        </div>
       </div>
      </div>
     </div>
     <div style="display:none">
      <div></div>
      <div></div>
     </div>
     <span><img src="https://facebook.com/security/hsts-pixel.gif" width="0" height="0" style="display:none"></span>
    </div>
    <div class=""></div>
    <div class="viewportArea _2v9s" style="display:none" id="u_0_4_Q/" data-sigil="marea">
     <div class="_5vsg" id="u_0_5_WK" style="max-height: 206px;"></div>
     <div class="_5vsh" id="u_0_6_N0" style="max-height: 376px;"></div>
     <div class="_5v5d fcg">
      <div class="_2so _2sq _2ss img _50cg" data-animtype="1" data-sigil="m-loading-indicator-animate m-loading-indicator-root"></div>Načítání…
     </div>
    </div>
    <div class="viewportArea aclb" id="mErrorView" style="display:none" data-sigil="marea">
     <div class="container">
      <div class="image"></div>
      <div class="message" data-sigil="error-message"></div>
      <a class="link" data-sigil="MPageError:retry">Opakovat</a>
     </div>
    </div>
   </div>
  </div>
  <div id="static_templates">
   <div class="mDialog" id="modalDialog" style="display:none" data-sigil=" context-layer-root" data-autoid="autoid_1">
    <div class="_52z5 _451a mFuturePageHeader _1uh1 firstStep titled" id="mDialogHeader">
     <div class="_7om2 _52we">
      <div class="_5s61">
       <div class="_52z7">
        <button type="submit" value="Zrušit" class="cancelButton btn btnD bgb mfss touchable" id="u_0_8_Kq" data-sigil="dialog-cancel-button">Zrušit</button>
        <button type="submit" value="Zpět" class="backButton btn btnI bgb mfss touchable iconOnly" aria-label="Zpět" id="u_0_9_KV" data-sigil="dialog-back-button"><i class="img sp_zqrNfmDGuGz_2x sx_336d05" style="margin-top: 2px;"></i></button>
       </div>
      </div>
      <div class="_4g34">
       <div class="_52z6">
        <div class="_50l4 mfsl fcw" id="m-future-page-header-title" role="heading" tabindex="0" data-sigil="m-dialog-header-title dialog-title">
         Načítání…
        </div>
       </div>
      </div>
      <div class="_5s61">
       <div class="_52z8" id="modalDialogHeaderButtons"></div>
      </div>
     </div>
    </div>
    <div class="modalDialogView" id="modalDialogView"></div>
    <div class="_5v5d _5v5e fcg" id="dialogSpinner">
     <div class="_2so _2sq _2ss img _50cg" data-animtype="1" id="u_0_7_vT" data-sigil="m-loading-indicator-animate m-loading-indicator-root"></div>Načítání…
    </div>
   </div>
  </div> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yu/l/0,cross/5KGrGpa-gBd.css?_nc_x=Ij3Wp8lg5Kz" as="style" crossorigin="anonymous"> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/y-/r/y6XwryXmYgW.js?_nc_x=Ij3Wp8lg5Kz" as="script" crossorigin="anonymous" nonce=""> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yc/l/0,cross/U0ygOl5bYc3.css?_nc_x=Ij3Wp8lg5Kz" as="style" crossorigin="anonymous"> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/ym/l/0,cross/H0XnjHPqhuJ.css?_nc_x=Ij3Wp8lg5Kz" as="style" crossorigin="anonymous"> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3i9io4/yU/l/cs_CZ/oteTkhi13Db.js?_nc_x=Ij3Wp8lg5Kz" as="script" crossorigin="anonymous" nonce=""> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3iQeB4/yz/l/cs_CZ/CAs4HwpQN7Q.js?_nc_x=Ij3Wp8lg5Kz" as="script" crossorigin="anonymous" nonce=""> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/e-09qslM9lx.js?_nc_x=Ij3Wp8lg5Kz" as="script" crossorigin="anonymous" nonce=""> 
  <link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yU/r/TeovwXu5GSv.js?_nc_x=Ij3Wp8lg5Kz" as="script" crossorigin="anonymous" nonce=""> 
  <div class="hidden_elem"></div> 
  <div class="AdBox Ad advert post-ads"></div>
  <div class="widgetSponsors"></div>
 </body>
</html>

**Comment by Rafael9812** [comment]
#43
